# Generated by Django 4.2.1 on 2023-05-21 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nuban',
            new_name='account_no',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default='location', max_length=70),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Job Title', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp601', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('luganda', 'LUGANDA')], default='english', max_length=10),
        ),
    ]
