# Generated by Django 4.2.1 on 2023-05-21 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_rename_nuban_employee_account_no_department_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp132', max_length=70),
        ),
    ]
